<?php

namespace Feature\Order;

use App\Models\User;

class OrderTest extends \TestCase
{
    private $headers;

    protected function setUp(): void
    {
        $this->headers = [
            'Authorization' => $this->getToken(1)
        ];
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWillReturnFieldRequiredIsEmpty()
    {
        $data = [];

        $this->post('api/order', $data, $this->headers)
            ->seeStatusCode(422)
            ->seeJson(["products" => ["The products field is required."]]);
    }

    public function testWillReturnInvalidProducts()
    {
        $data = [
            'products' => [
                []
            ]
        ];

        $this->post('api/order', $data, $this->headers)
            ->seeStatusCode(400)
            ->seeJsonStructure([
                'error', 'message'
            ]);
    }

    public function testWillInsertAOrder()
    {
        $data = [
            'products' => [
                [ 'id' => 1 ]
            ]
        ];

        $this->post('api/order', $data, $this->headers)
            ->seeStatusCode(200);
    }

    public function getToken(int $id)
    {
        return (new User())->setId($id)->getToken();
    }
}
