<?php

namespace Feature\Products;

use App\Models\User;

class ProductsTest extends \TestCase
{
    private $token_jwt;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWillReturnTheProduct()
    {
        $this->token_jwt = $this->getToken(1);

        $result = $this->get('/api/products/1', [
            'Authorization' => $this->token_jwt
        ]);

        $result->seeJsonStructure([
            'data' => [
                'id', 'name', 'value', 'quantity'
            ]
        ]);
    }

    public function willReturnUnauthorizedWhenPassANotValidToken()
    {
        $result = $this->get('products', [
            'Authorization' => (new User())->setId(10)->getToken()
        ]);

        $result->seeJsonEquals([
            'error' => 'Unauthorized'
        ]);

        $result->seeStatusCode(401);
    }

    public function getToken(int $id)
    {
        return (new User())->setId($id)->getToken();
    }
}
