<?php

namespace Feature\Products;

use App\Models\User;

class ProductsTest extends \TestCase
{
    private $token_jwt;

    protected function setUp(): void
    {
        $this->token_jwt = $this->getToken(1);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWillReturnTheProduct()
    {
        $result = $this->get('/api/products/1', [
            'Authorization' => $this->token_jwt
        ]);

        $result->seeJsonStructure([
            'data' => [
                'id', 'name', 'value', 'quantity'
            ]
        ]);
    }

    public function testWillReturnErrorWhenPassInvalidId()
    {
        $this->get('/api/products/AAA', [ 'Authorization' => $this->token_jwt ])
            ->seeStatusCode(500);
    }

    public function testWillReturnTheProducts()
    {
        $this->get('api/products', ['Authorization' => $this->token_jwt])
            ->seeStatusCode(200)
            ->seeJsonStructure([
                'data' => [
                    ['id', 'name', 'value', 'quantity']
                ]
            ]);
    }

    public function getToken(int $id)
    {
        return (new User())->setId($id)->getToken();
    }
}
