<?php

namespace Feature\Products;

use App\Models\User;
use Firebase\JWT\JWT;

class ProductsTest extends \TestCase
{
    private $token_jwt;

    protected function setUp(): void
    {
        $this->token_jwt = (new User())->setId(2)->getToken();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWillReturnTheProduct()
    {
        $result = $this->get('/api/products/1', [
            'Authorization' => $this->token_jwt
        ]);

        $result->seeJsonStructure([
            'data' => [
                'id', 'name', 'value', 'quantity'
            ]
        ]);
    }
}
